#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import os
from datetime import timedelta


def seconds_to_ass_timestamp(seconds):
    """将秒数转换为ASS字幕时间戳格式 (HH:MM:SS.cc)"""
    td = timedelta(seconds=seconds)
    hours, remainder = divmod(td.seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    milliseconds = td.microseconds // 10000  # 转换为百分之一秒(centiseconds)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}.{milliseconds:02d}"


def json_to_ass(json_file_path, ass_file_path=None, title="Default Title",
                font_name="Microsoft YaHei", font_size=14,
                primary_color="&H00FFFFFF", secondary_color="&H000000FF",
                outline_color="&H00000000", back_color="&H00000000",
                bold=0, italic=0, underline=0, strikeout=0,
                scale_x=100, scale_y=100, spacing=0, angle=0,
                border_style=1, outline=2, shadow=0,
                alignment=2, margin_l=10, margin_r=10, margin_v=10):
    """
    将JSON字幕文件转换为ASS字幕文件

    参数:
    json_file_path: JSON文件路径
    ass_file_path: 输出的ASS文件路径，默认为输入文件路径替换扩展名为.ass
    title: 字幕标题
    font_name: 字体名称
    font_size: 字体大小
    primary_color: 主要颜色 (&HBBGGRR format)
    secondary_color: 次要颜色
    outline_color: 轮廓颜色
    back_color: 背景颜色
    bold: 粗体 (0 or 1)
    italic: 斜体 (0 or 1)
    underline: 下划线 (0 or 1)
    strikeout: 删除线 (0 or 1)
    scale_x: X轴缩放
    scale_y: Y轴缩放
    spacing: 字符间距
    angle: 旋转角度
    border_style: 边框样式 (1=轮廓+阴影, 3=背景框)
    outline: 轮廓大小
    shadow: 阴影大小
    alignment: 对齐方式 (1=左下, 2=中下, 3=右下, etc.)
    margin_l: 左边距
    margin_r: 右边距
    margin_v: 垂直边距
    """

    # 如果未指定输出文件路径，则使用默认路径
    if ass_file_path is None:
        base_name = os.path.splitext(json_file_path)[0]
        ass_file_path = base_name + ".ass"

    # 读取JSON文件
    with open(json_file_path, 'r', encoding='utf-8') as f:
        subtitles = json.load(f)

    # 创建ASS文件
    with open(ass_file_path, 'w', encoding='utf-8') as f:
        # 写入ASS文件头
        f.write("""[Script Info]
; Script generated by json_to_ass_converter
Title: {}
ScriptType: v4.00+
Collisions: Normal
PlayDepth: 0
Timer: 100.0000
WrapStyle: 0

""".format(title))

        # 写入样式信息
        f.write("""[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},1

""".format(
            font_name, font_size, primary_color, secondary_color, outline_color, back_color,
            bold, italic, underline, strikeout, scale_x, scale_y, spacing, angle,
            border_style, outline, shadow, alignment, margin_l, margin_r, margin_v
        ))

        # 写入事件头部
        f.write("""[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
""")

        # 写入字幕事件
        for i, subtitle in enumerate(subtitles, 1):
            start_time = seconds_to_ass_timestamp(subtitle["start"])
            end_time = seconds_to_ass_timestamp(subtitle["end"])
            text = subtitle["text"].replace("\n", "\\N")  # 替换换行符

            f.write(f"Dialogue: 0,{start_time},{end_time},Default,,0,0,0,,{text}\n")

    print(f"已成功转换 '{json_file_path}' 到 '{ass_file_path}'")
    return ass_file_path


def main():
    """主函数，用于命令行调用"""
    import argparse

    parser = argparse.ArgumentParser(description='将JSON字幕文件转换为ASS格式')
    parser.add_argument('input', default=r"W:\work\MediaAgents\MetaHuman\worker\temp\sentences_1214.json", help='输入的JSON文件路径')
    parser.add_argument('-o', default="./aaa.ass", help='输出的ASS文件路径')
    parser.add_argument('--title', default='Default Title', help='字幕标题')
    parser.add_argument('--font-name', default='Microsoft YaHei', help='字体名称')
    parser.add_argument('--font-size', type=int, default=16, help='字体大小')

    # args = parser.parse_args()

    json_to_ass(
        r"W:\work\MediaAgents\MetaHuman\worker\work4x\workers\video_utils\sentences_output_split_if_exceeds.json",
        "./output.ass",
        title="aaabbb",
        font_name="Microsoft YaHei",
        font_size=16
    )


if __name__ == "__main__":
    main()
